# ==============================================================================
# Merged Lakeflow Source: braze
# ==============================================================================
# This file is auto-generated by tools/scripts/merge_python_source.py
# Do not edit manually. Make changes to the source files instead.
# ==============================================================================

from abc import ABC, abstractmethod
from datetime import datetime, timedelta, timezone
from decimal import Decimal
from typing import Any, Iterator, Sequence
import json
import time

from pyspark.sql import Row
from pyspark.sql.datasource import (
    DataSource,
    DataSourceReader,
    DataSourceStreamReader,
    InputPartition,
    SimpleDataSourceStreamReader,
)
from pyspark.sql.streaming.datasource import ReadAllAvailable, SupportsTriggerAvailableNow
from pyspark.sql.types import (
    ArrayType,
    BinaryType,
    BooleanType,
    DataType,
    DateType,
    DecimalType,
    DoubleType,
    FloatType,
    IntegerType,
    LongType,
    MapType,
    StringType,
    StructField,
    StructType,
    TimestampType,
    VariantType,
    VariantVal,
)
import base64
import math
import requests


def register_lakeflow_source(spark):
    """Register the Lakeflow Python source with Spark."""

    ########################################################
    # src/databricks/labs/community_connector/libs/utils.py
    ########################################################

    def _parse_struct(value: Any, field_type: StructType) -> Row:
        """Parse a dictionary into a PySpark Row based on StructType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for StructType, got {type(value)}")
        # Spark Python -> Arrow conversion require missing StructType fields to be assigned None.
        if value == {}:
            raise ValueError(
                "field in StructType cannot be an empty dict. "
                "Please assign None as the default value instead."
            )
        field_dict = {}
        for field in field_type.fields:
            if field.name in value:
                field_dict[field.name] = parse_value(value.get(field.name), field.dataType)
            elif field.nullable:
                field_dict[field.name] = None
            else:
                raise ValueError(f"Field {field.name} is not nullable but not found in the input")
        return Row(**field_dict)


    def _parse_array(value: Any, field_type: ArrayType) -> list:
        """Parse a list into a PySpark array based on ArrayType schema."""
        if not isinstance(value, list):
            if field_type.containsNull:
                return [parse_value(value, field_type.elementType)]
            raise ValueError(f"Expected a list for ArrayType, got {type(value)}")
        return [parse_value(v, field_type.elementType) for v in value]


    def _parse_map(value: Any, field_type: MapType) -> dict:
        """Parse a dictionary into a PySpark map based on MapType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for MapType, got {type(value)}")
        return {
            parse_value(k, field_type.keyType): parse_value(v, field_type.valueType)
            for k, v in value.items()
        }


    def _parse_string(value: Any) -> str:
        """Convert value to string."""
        return str(value)


    def _parse_integer(value: Any) -> int:
        """Convert value to integer."""
        if isinstance(value, str) and value.strip():
            return int(float(value)) if "." in value else int(value)
        if isinstance(value, (int, float)):
            return int(value)
        raise ValueError(f"Cannot convert {value} to integer")


    def _parse_float(value: Any) -> float:
        """Convert value to float."""
        return float(value)


    def _parse_decimal(value: Any) -> Decimal:
        """Convert value to Decimal."""
        return Decimal(value) if isinstance(value, str) and value.strip() else Decimal(str(value))


    def _parse_boolean(value: Any) -> bool:
        """Convert value to boolean."""
        if isinstance(value, str):
            lowered = value.lower()
            if lowered in ("true", "t", "yes", "y", "1"):
                return True
            if lowered in ("false", "f", "no", "n", "0"):
                return False
        return bool(value)


    def _parse_date(value: Any) -> datetime.date:
        """Convert value to date."""
        if isinstance(value, str):
            for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%d-%m-%Y", "%Y/%m/%d"):
                try:
                    return datetime.strptime(value, fmt).date()
                except ValueError:
                    continue
            return datetime.fromisoformat(value).date()
        if isinstance(value, datetime):
            return value.date()
        raise ValueError(f"Cannot convert {value} to date")


    def _parse_timestamp(value: Any) -> datetime:
        """Convert value to timestamp."""
        if isinstance(value, str):
            ts_value = value.replace("Z", "+00:00") if value.endswith("Z") else value
            try:
                return datetime.fromisoformat(ts_value)
            except ValueError:
                for fmt in ("%Y-%m-%d %H:%M:%S", "%Y/%m/%d %H:%M:%S"):
                    try:
                        return datetime.strptime(ts_value, fmt)
                    except ValueError:
                        continue
        elif isinstance(value, (int, float)):
            return datetime.fromtimestamp(value)
        elif isinstance(value, datetime):
            return value
        raise ValueError(f"Cannot convert {value} to timestamp")


    def _decode_string_to_bytes(value: str) -> bytes:
        """Try to decode a string as base64, then hex, then UTF-8."""
        try:
            return base64.b64decode(value)
        except Exception:
            pass
        try:
            return bytes.fromhex(value)
        except Exception:
            pass
        return value.encode("utf-8")


    def _parse_binary(value: Any) -> bytes:
        """Convert value to bytes. Tries base64, then hex, then UTF-8 for strings."""
        if isinstance(value, bytes):
            return value
        if isinstance(value, bytearray):
            return bytes(value)
        if isinstance(value, str):
            return _decode_string_to_bytes(value)
        if isinstance(value, list):
            return bytes(value)
        return str(value).encode("utf-8")


    # Mapping of primitive types to their parser functions
    _PRIMITIVE_PARSERS = {
        StringType: _parse_string,
        IntegerType: _parse_integer,
        LongType: _parse_integer,
        FloatType: _parse_float,
        DoubleType: _parse_float,
        DecimalType: _parse_decimal,
        BooleanType: _parse_boolean,
        DateType: _parse_date,
        TimestampType: _parse_timestamp,
        BinaryType: _parse_binary,
    }


    def parse_value(value: Any, field_type: DataType) -> Any:  # pylint: disable=too-many-return-statements
        """
        Converts a JSON value into a PySpark-compatible data type based on the provided field type.
        """
        if value is None:
            return None

        # Handle complex types
        if isinstance(field_type, StructType):
            return _parse_struct(value, field_type)
        if isinstance(field_type, ArrayType):
            return _parse_array(value, field_type)
        if isinstance(field_type, MapType):
            return _parse_map(value, field_type)

        # Handle VariantType
        if isinstance(field_type, VariantType):
            return VariantVal.parseJson(value) if isinstance(value, str) else value

        # Handle primitive types via type-based lookup
        try:
            field_type_class = type(field_type)
            if field_type_class in _PRIMITIVE_PARSERS:
                return _PRIMITIVE_PARSERS[field_type_class](value)

            # Check for custom UDT handling
            if hasattr(field_type, "fromJson"):
                return field_type.fromJson(value)

            raise TypeError(f"Unsupported field type: {field_type}")
        except (ValueError, TypeError) as e:
            raise ValueError(f"Error converting '{value}' ({type(value)}) to {field_type}: {str(e)}")


    ########################################################
    # src/databricks/labs/community_connector/interface/lakeflow_connect.py
    ########################################################

    class LakeflowConnect(ABC):
        """Base interface that each source connector must implement.

        Subclass this and implement all abstract methods to create a connector that
        integrates with the community connector library and ingestion pipeline.
        """

        def __init__(self, options: dict[str, str]) -> None:
            """
            Initialize the source connector with parameters needed to connect to the source.
            Args:
                options: A dictionary of parameters like authentication tokens, table names,
                    and other configurations.
            """
            self.options = options

        @abstractmethod
        def list_tables(self) -> list[str]:
            """
            List names of all the tables supported by the source connector.
            The list could either be a static list or retrieved from the source via API.
            Returns:
                A list of table names.
            """

        @abstractmethod
        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            """
            Fetch the schema of a table.
            Args:
                table_name: The name of the table to fetch the schema for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the schema.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A StructType object representing the schema of the table.
            """

        @abstractmethod
        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            """
            Fetch the metadata of a table.
            Args:
                table_name: The name of the table to fetch the metadata for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the metadata.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A dictionary containing the metadata of the table. It should include the
                following keys:
                    - primary_keys: List of string names of the primary key columns of
                        the table.
                    - cursor_field: The name of the field to use as a cursor for
                        incremental loading.
                    - ingestion_type: The type of ingestion to use for the table. It
                        should be one of the following values:
                        - "snapshot": For snapshot loading.
                        - "cdc": Capture incremental changes (no delete support).
                        - "cdc_with_deletes": Capture incremental changes with delete
                            support. Requires implementing read_table_deletes().
                        - "append": Incremental append.
            """

        @abstractmethod
        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read the records of a table and return an iterator of records and an offset.

            The framework calls this method repeatedly to paginate through data.
            start_offset is None only on the very first call of the very first run
            of a connector. On subsequent runs the framework resumes from the last
            checkpointed offset, so start_offset will already be populated. Each
            call returns (records, end_offset). The framework passes end_offset as
            start_offset to the next call. Pagination stops when the returned
            offset equals start_offset (i.e., no more data).

            For tables that cannot be incrementally read, return None as the offset to
            read the entire table in one batch. Non-checkpointable synthetic offsets can
            be used to split the data into multiple batches.

            Args:
                table_name: The name of the table to read.
                start_offset: The offset to start reading from. None only on the
                    first call of the first run; on subsequent runs it carries the
                    checkpointed offset from the previous run.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to read the table.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of records as JSON-compatible dicts. Do NOT convert
                    values according to get_table_schema(); the framework handles that.
                offset: A dict representing the position after this batch.
            """

        def read_table_deletes(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read deleted records from a table for CDC delete synchronization.
            This method is called when ingestion_type is "cdc_with_deletes" to fetch
            records that have been deleted from the source system.

            This method follows the same pagination and offset protocol as read_table:
            the framework calls it repeatedly, passing the previous end_offset as
            start_offset, until the returned offset equals start_offset.

            Override this method if any of your tables use ingestion_type
            "cdc_with_deletes". The default implementation raises NotImplementedError.

            The returned records should have at minimum the primary key fields and
            cursor field populated. Other fields can be null.

            Args:
                table_name: The name of the table to read deleted records from.
                start_offset: The offset to start reading from (same format as read_table).
                table_options: A dictionary of options for accessing the table.
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of deleted records (must include primary keys and cursor).
                offset: A dict (same format as read_table).
            """
            raise NotImplementedError(
                "read_table_deletes() must be implemented when ingestion_type is 'cdc_with_deletes'"
            )


    ########################################################
    # src/databricks/labs/community_connector/interface/supports_partition.py
    ########################################################

    class SupportsPartition(ABC):
        """Mixin for connectors that support partitioned reads across Spark executors.

        Must be used together with LakeflowConnect. Implement this when your
        connector can split work into partitions that Spark distributes to workers,
        instead of reading all data in one partition batch.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartition):
                ...
        """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """

        @abstractmethod
        def read_partition(
            self, table_name: str, partition: dict, table_options: dict[str, str]
        ) -> Iterator[dict]:
            """Read records for a single partition.

            This method runs on Spark executors and must be self-contained.

            Args:
                table_name: The name of the table.
                partition: One of the partition dicts returned by
                    :meth:`get_partitions`.
                table_options: A dictionary of options for accessing the table.
            Returns:
                An iterator of records as JSON-compatible dicts.
            """


    class SupportsPartitionedStream(SupportsPartition):
        """Mixin for connectors that support partitioned streaming reads.

        Extends :class:`SupportsPartition` with offset awareness for streaming
        micro-batches. A connector implementing this mixin automatically supports
        both partitioned batch reads (via the inherited interface) and partitioned
        streaming reads.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartitionedStream):
                ...
        """

        def is_partitioned(self, table_name: str) -> bool:
            """Return whether the given table supports partitioned streaming.

            The default returns True. Override to return False for tables that
            should fall back to simpleStreamReader.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            """
            return True

        @abstractmethod
        def latest_offset(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
        ) -> dict:
            """Return the most recent offset available for the table.

            Called by Spark on every micro-batch to discover new data.

            Micro-batch sizing (by row count, time window, etc.) is entirely the
            connector's responsibility — use table_options (e.g. ``window_days``,
            ``max_records_per_batch``) to control it.  The framework always
            requests "all available" and does not pass an admission-control
            hint here.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The current committed offset.  ``{}`` on the very
                    first call (from ``initialOffset``), then the last returned
                    end_offset on each subsequent call.
            Returns:
                A dict whose keys and values are primitive types (str, int, bool).
            """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
            end_offset: dict | None = None,
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            For batch reads, ``start_offset`` and ``end_offset`` are both None —
            return partitions covering the entire table.

            For streaming micro-batches, they delimit the offset range — return
            partitions covering that range, or an empty sequence when
            ``start_offset == end_offset``.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The start offset (exclusive), or None for batch.
                end_offset: The end offset (inclusive), or None for batch.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """


    ########################################################
    # src/databricks/labs/community_connector/interface/supports_namespaces.py
    ########################################################

    class SupportsNamespaces(ABC):
        """Mixin for connectors whose tables live under hierarchical namespaces.

        A namespace is a path of zero or more string segments (e.g. ``["org",
        "repo"]`` for GitHub, ``["tenant", "project"]`` for Azure DevOps).
        Connectors with a flat catalog do not need this mixin — the framework
        falls back to :meth:`LakeflowConnect.list_tables` and reports each table
        with an empty namespace.

        Output ordering on the ``_community_namespaces`` and ``_community_tables``
        Spark virtual tables is normalized by the framework via ``sorted(...)``,
        so connector implementations of :meth:`list_namespaces` and
        :meth:`list_tables_in_namespace` are free to return their results in
        any order (including from a :class:`set` or generator).

        Must be used together with :class:`LakeflowConnect`.

        Usage::

            class MyConnector(LakeflowConnect, SupportsNamespaces):
                ...
        """

        @abstractmethod
        def list_namespaces(
            self,
            prefix: list[str] | None = None,
        ) -> list[list[str]]:
            """Return the immediate child namespaces under ``prefix``.

            This method returns one level of *namespace* children only — it
            never returns tables. A namespace can hold tables and child
            namespaces independently; callers must always call
            :meth:`list_tables_in_namespace` for every namespace they care
            about, regardless of whether :meth:`list_namespaces` returned
            children for it. An empty return value just means there are no
            further child namespaces under ``prefix``.

            Walk the full tree by recursing on each returned child.

            Args:
                prefix: A namespace path under which to list children. ``None`` or
                    an empty list lists the root-level namespaces.
            Returns:
                A list of full namespace paths (each path includes the prefix).
            """

        @abstractmethod
        def list_tables_in_namespace(
            self,
            namespace: list[str],
        ) -> list[str]:
            """Return the table names that live directly under ``namespace``.

            Callers that want every table across the whole catalog walk the
            namespace tree via :meth:`list_namespaces` and call this method
            once per leaf — there is no "list everything" shortcut.

            Args:
                namespace: The namespace path. An empty list ``[]`` selects
                    root-level tables (those that live outside any namespace).
            Returns:
                A list of table names. The full ``(namespace, table_name)``
                row exposed on ``_community_tables`` is reconstructed by the
                framework from the namespace the caller already supplied, so
                the connector does not need to echo it back.
            """


    ########################################################
    # src/databricks/labs/community_connector/sources/braze/braze_schemas.py
    ########################################################

    RETRIABLE_STATUS_CODES = {429, 500, 502, 503, 504}
    MAX_RETRIES = 5
    INITIAL_BACKOFF = 1.0  # seconds; doubled after each retry
    REQUEST_TIMEOUT = 30  # seconds; every HTTP call must set an explicit timeout

    # ---------------------------------------------------------------------------
    # Stream "kinds" — how a table is read.
    # ---------------------------------------------------------------------------
    #   snapshot_list    : paginated list endpoint, full-refresh snapshot.
    #   details          : two-step fan-out (list -> details, one call per id),
    #                      snapshot; not date-windowed.
    #   fanout_analytics : date-windowed ``data_series`` endpoint fanned out per
    #                      parent id/name discovered from a list endpoint.
    #   workspace_series : date-windowed ``data_series`` endpoint at the
    #                      workspace/app level (no fan-out).
    KIND_SNAPSHOT_LIST = "snapshot_list"
    KIND_DETAILS = "details"
    KIND_FANOUT_ANALYTICS = "fanout_analytics"
    KIND_WORKSPACE_SERIES = "workspace_series"

    # Deprecated News Feed streams (Braze /feed/* endpoints). Kept for parity with
    # the documented catalogue; can be dropped from ``list_tables`` via the
    # ``include_deprecated_streams`` connection option.
    DEPRECATED_TABLES = ("cards", "cards_analytics")


    # ---------------------------------------------------------------------------
    # Reusable field groups
    # ---------------------------------------------------------------------------
    def _tags() -> StructField:
        return StructField("tags", ArrayType(StringType()), True)


    # ===========================================================================
    # Schemas
    # ===========================================================================
    CAMPAIGNS_SCHEMA = StructType(
        [
            StructField("id", StringType(), False),
            StructField("name", StringType(), True),
            StructField("is_api_campaign", BooleanType(), True),
            StructField("last_edited", StringType(), True),
            _tags(),
        ]
    )

    CAMPAIGNS_DETAILS_SCHEMA = StructType(
        [
            StructField("campaign_id", StringType(), False),
            StructField("created_at", StringType(), True),
            StructField("updated_at", StringType(), True),
            StructField("archived", BooleanType(), True),
            StructField("draft", BooleanType(), True),
            StructField("enabled", BooleanType(), True),
            StructField("has_post_launch_draft", BooleanType(), True),
            StructField("name", StringType(), True),
            StructField("description", StringType(), True),
            StructField("schedule_type", StringType(), True),
            StructField("channels", ArrayType(StringType()), True),
            StructField("first_sent", StringType(), True),
            StructField("last_sent", StringType(), True),
            _tags(),
            StructField("teams", ArrayType(StringType()), True),
            # Dynamic (keyed by message-variation id / channel) -> JSON string.
            StructField("messages", StringType(), True),
            # Array of conversion-behaviour objects -> JSON string.
            StructField("conversion_behaviors", StringType(), True),
        ]
    )

    CAMPAIGNS_ANALYTICS_SCHEMA = StructType(
        [
            StructField("campaign_id", StringType(), False),
            StructField("time", StringType(), False),
            StructField("conversions", LongType(), True),
            StructField("conversions1", LongType(), True),
            StructField("conversions2", LongType(), True),
            StructField("conversions3", LongType(), True),
            StructField("conversions_by_send_time", LongType(), True),
            StructField("conversions1_by_send_time", LongType(), True),
            StructField("unique_recipients", LongType(), True),
            StructField("revenue", DoubleType(), True),
            # Channel-keyed metrics -> JSON string.
            StructField("messages", StringType(), True),
        ]
    )

    CANVASES_SCHEMA = StructType(
        [
            StructField("id", StringType(), False),
            StructField("name", StringType(), True),
            StructField("last_edited", StringType(), True),
            _tags(),
        ]
    )

    CANVASES_DETAILS_SCHEMA = StructType(
        [
            StructField("canvas_id", StringType(), False),
            StructField("created_at", StringType(), True),
            StructField("updated_at", StringType(), True),
            StructField("name", StringType(), True),
            StructField("description", StringType(), True),
            StructField("archived", BooleanType(), True),
            StructField("draft", BooleanType(), True),
            StructField("enabled", BooleanType(), True),
            StructField("has_post_launch_draft", BooleanType(), True),
            StructField("schedule_type", StringType(), True),
            StructField("first_entry", StringType(), True),
            StructField("last_entry", StringType(), True),
            StructField("channels", ArrayType(StringType()), True),
            # Array of variant objects -> JSON string.
            StructField("variants", StringType(), True),
            _tags(),
            StructField("teams", ArrayType(StringType()), True),
            # Array of step objects -> JSON string.
            StructField("steps", StringType(), True),
        ]
    )

    _CANVAS_TOTAL_STATS = StructType(
        [
            StructField("revenue", DoubleType(), True),
            StructField("conversions", LongType(), True),
            StructField("conversions_by_entry_time", LongType(), True),
            StructField("entries", LongType(), True),
        ]
    )

    CANVASES_ANALYTICS_SCHEMA = StructType(
        [
            StructField("canvas_id", StringType(), False),
            StructField("time", StringType(), False),
            StructField("total_stats", _CANVAS_TOTAL_STATS, True),
            # Per-variant / per-step stats (keyed by variant/step id) -> JSON.
            StructField("variant_stats", StringType(), True),
            StructField("step_stats", StringType(), True),
        ]
    )

    SEGMENTS_SCHEMA = StructType(
        [
            StructField("id", StringType(), False),
            StructField("name", StringType(), True),
            StructField("analytics_tracking_enabled", BooleanType(), True),
            _tags(),
        ]
    )

    SEGMENTS_DETAILS_SCHEMA = StructType(
        [
            StructField("segment_id", StringType(), False),
            StructField("created_at", StringType(), True),
            StructField("updated_at", StringType(), True),
            StructField("name", StringType(), True),
            StructField("description", StringType(), True),
            StructField("text_description", StringType(), True),
            _tags(),
            StructField("teams", ArrayType(StringType()), True),
        ]
    )

    SEGMENTS_ANALYTICS_SCHEMA = StructType(
        [
            StructField("segment_id", StringType(), False),
            StructField("time", StringType(), False),
            StructField("size", LongType(), True),
        ]
    )

    EVENTS_SCHEMA = StructType(
        [
            StructField("event", StringType(), False),
        ]
    )

    EVENTS_ANALYTICS_SCHEMA = StructType(
        [
            StructField("event", StringType(), False),
            StructField("time", StringType(), False),
            StructField("count", LongType(), True),
        ]
    )

    CARDS_SCHEMA = StructType(
        [
            StructField("id", StringType(), False),
            StructField("name", StringType(), True),
            _tags(),
        ]
    )

    CARDS_ANALYTICS_SCHEMA = StructType(
        [
            StructField("card_id", StringType(), False),
            StructField("time", StringType(), False),
            StructField("clicks", LongType(), True),
            StructField("impressions", LongType(), True),
            StructField("unique_clicks", LongType(), True),
            StructField("unique_impressions", LongType(), True),
        ]
    )

    KPI_NEW_USERS_SCHEMA = StructType(
        [
            StructField("time", StringType(), False),
            StructField("new_users", LongType(), True),
        ]
    )

    KPI_DAU_SCHEMA = StructType(
        [
            StructField("time", StringType(), False),
            StructField("dau", LongType(), True),
        ]
    )

    KPI_MAU_SCHEMA = StructType(
        [
            StructField("time", StringType(), False),
            StructField("mau", LongType(), True),
        ]
    )

    KPI_UNINSTALLS_SCHEMA = StructType(
        [
            StructField("time", StringType(), False),
            StructField("uninstalls", LongType(), True),
        ]
    )

    PURCHASES_PRODUCT_LIST_SCHEMA = StructType(
        [
            StructField("product", StringType(), False),
        ]
    )

    PURCHASES_QUANTITY_SERIES_SCHEMA = StructType(
        [
            StructField("time", StringType(), False),
            StructField("purchase_quantity", LongType(), True),
        ]
    )

    PURCHASES_REVENUE_SERIES_SCHEMA = StructType(
        [
            StructField("time", StringType(), False),
            # Doc shows int, but revenue can be fractional in practice -> Double.
            StructField("revenue", DoubleType(), True),
        ]
    )

    SENDS_ANALYTICS_SCHEMA = StructType(
        [
            StructField("campaign_id", StringType(), False),
            StructField("send_id", StringType(), False),
            StructField("time", StringType(), False),
            StructField("messages", StringType(), True),  # channel-keyed -> JSON
            StructField("sent", LongType(), True),
            StructField("delivered", LongType(), True),
            StructField("undelivered", LongType(), True),
            StructField("delivery_failed", LongType(), True),
            StructField("direct_opens", LongType(), True),
            StructField("total_opens", LongType(), True),
            StructField("bounces", LongType(), True),
            StructField("body_clicks", LongType(), True),
            StructField("revenue", DoubleType(), True),
            StructField("unique_recipients", LongType(), True),
            StructField("conversions", LongType(), True),
            StructField("conversions_by_send_time", LongType(), True),
            StructField("conversions1", LongType(), True),
            StructField("conversions2", LongType(), True),
            StructField("conversions3", LongType(), True),
        ]
    )


    TABLE_SCHEMAS: dict[str, StructType] = {
        "campaigns": CAMPAIGNS_SCHEMA,
        "campaigns_details": CAMPAIGNS_DETAILS_SCHEMA,
        "campaigns_analytics": CAMPAIGNS_ANALYTICS_SCHEMA,
        "canvases": CANVASES_SCHEMA,
        "canvases_details": CANVASES_DETAILS_SCHEMA,
        "canvases_analytics": CANVASES_ANALYTICS_SCHEMA,
        "segments": SEGMENTS_SCHEMA,
        "segments_details": SEGMENTS_DETAILS_SCHEMA,
        "segments_analytics": SEGMENTS_ANALYTICS_SCHEMA,
        "events": EVENTS_SCHEMA,
        "events_analytics": EVENTS_ANALYTICS_SCHEMA,
        "cards": CARDS_SCHEMA,
        "cards_analytics": CARDS_ANALYTICS_SCHEMA,
        "kpi_daily_new_users": KPI_NEW_USERS_SCHEMA,
        "kpi_daily_active_users": KPI_DAU_SCHEMA,
        "kpi_monthly_active_users": KPI_MAU_SCHEMA,
        "kpi_daily_app_uninstalls": KPI_UNINSTALLS_SCHEMA,
        "purchases_product_list": PURCHASES_PRODUCT_LIST_SCHEMA,
        "purchases_quantity_series": PURCHASES_QUANTITY_SERIES_SCHEMA,
        "purchases_revenue_series": PURCHASES_REVENUE_SERIES_SCHEMA,
        "sends_analytics": SENDS_ANALYTICS_SCHEMA,
    }

    # Static catalogue ordering used by ``list_tables``.
    SUPPORTED_TABLES: tuple[str, ...] = tuple(TABLE_SCHEMAS.keys())


    # ===========================================================================
    # Metadata (primary_keys / cursor_field / ingestion_type)
    # ===========================================================================
    _SNAPSHOT = "snapshot"
    _APPEND = "append"

    TABLE_METADATA: dict[str, dict] = {
        "campaigns": {
            "primary_keys": ["id"], "cursor_field": None,
            "ingestion_type": _SNAPSHOT,
        },
        "campaigns_details": {
            "primary_keys": ["campaign_id"], "cursor_field": None,
            "ingestion_type": _SNAPSHOT,
        },
        "campaigns_analytics": {
            "primary_keys": ["campaign_id", "time"], "cursor_field": "time",
            "ingestion_type": _APPEND,
        },
        "canvases": {
            "primary_keys": ["id"], "cursor_field": None,
            "ingestion_type": _SNAPSHOT,
        },
        "canvases_details": {
            "primary_keys": ["canvas_id"], "cursor_field": None,
            "ingestion_type": _SNAPSHOT,
        },
        "canvases_analytics": {
            "primary_keys": ["canvas_id", "time"], "cursor_field": "time",
            "ingestion_type": _APPEND,
        },
        "segments": {
            "primary_keys": ["id"], "cursor_field": None,
            "ingestion_type": _SNAPSHOT,
        },
        "segments_details": {
            "primary_keys": ["segment_id"], "cursor_field": None,
            "ingestion_type": _SNAPSHOT,
        },
        "segments_analytics": {
            "primary_keys": ["segment_id", "time"], "cursor_field": "time",
            "ingestion_type": _APPEND,
        },
        "events": {
            "primary_keys": ["event"], "cursor_field": None,
            "ingestion_type": _SNAPSHOT,
        },
        "events_analytics": {
            "primary_keys": ["event", "time"], "cursor_field": "time",
            "ingestion_type": _APPEND,
        },
        "cards": {
            "primary_keys": ["id"], "cursor_field": None,
            "ingestion_type": _SNAPSHOT,
        },
        "cards_analytics": {
            "primary_keys": ["card_id", "time"], "cursor_field": "time",
            "ingestion_type": _APPEND,
        },
        "kpi_daily_new_users": {
            "primary_keys": ["time"], "cursor_field": "time",
            "ingestion_type": _APPEND,
        },
        "kpi_daily_active_users": {
            "primary_keys": ["time"], "cursor_field": "time",
            "ingestion_type": _APPEND,
        },
        "kpi_monthly_active_users": {
            "primary_keys": ["time"], "cursor_field": "time",
            "ingestion_type": _APPEND,
        },
        "kpi_daily_app_uninstalls": {
            "primary_keys": ["time"], "cursor_field": "time",
            "ingestion_type": _APPEND,
        },
        "purchases_product_list": {
            "primary_keys": ["product"], "cursor_field": None,
            "ingestion_type": _SNAPSHOT,
        },
        "purchases_quantity_series": {
            "primary_keys": ["time"], "cursor_field": "time",
            "ingestion_type": _APPEND,
        },
        "purchases_revenue_series": {
            "primary_keys": ["time"], "cursor_field": "time",
            "ingestion_type": _APPEND,
        },
        "sends_analytics": {
            "primary_keys": ["campaign_id", "send_id", "time"],
            "cursor_field": "time", "ingestion_type": _APPEND,
        },
    }


    # ===========================================================================
    # Per-stream routing config.
    # ===========================================================================
    # Braze list-endpoint page sizes (documented). Used only to decide when the
    # last (short) page has been reached; the connector paginates 0-indexed.
    _PAGE_SIZE_DEFAULT = 100
    _PAGE_SIZE_EVENTS = 250

    # Maximum date-window (in days) each analytics endpoint accepts in one call.
    MAX_WINDOW_DAYS: dict[str, int] = {
        "campaigns_analytics": 100,
        "canvases_analytics": 14,
        "segments_analytics": 100,
        "events_analytics": 100,
        "cards_analytics": 100,
        "kpi_daily_new_users": 100,
        "kpi_daily_active_users": 100,
        "kpi_monthly_active_users": 100,
        "kpi_daily_app_uninstalls": 100,
        "purchases_quantity_series": 100,
        "purchases_revenue_series": 100,
        # Braze only retains send-level analytics for 14 days.
        "sends_analytics": 14,
    }

    # Snapshot list streams: path + envelope key + whether the array holds bare
    # strings (event names / product names) rather than objects.
    LIST_STREAMS: dict[str, dict] = {
        "campaigns": {
            "path": "/campaigns/list", "records_key": "campaigns",
            "page_size": _PAGE_SIZE_DEFAULT, "string_items": False,
        },
        "canvases": {
            "path": "/canvas/list", "records_key": "canvases",
            "page_size": _PAGE_SIZE_DEFAULT, "string_items": False,
        },
        "segments": {
            "path": "/segments/list", "records_key": "segments",
            "page_size": _PAGE_SIZE_DEFAULT, "string_items": False,
        },
        "events": {
            "path": "/events/list", "records_key": "events",
            "page_size": _PAGE_SIZE_EVENTS, "string_items": True,
            "string_field": "event",
        },
        "cards": {
            "path": "/feed/list", "records_key": "cards",
            "page_size": _PAGE_SIZE_DEFAULT, "string_items": False,
        },
        "purchases_product_list": {
            "path": "/purchases/product_list", "records_key": "products",
            "page_size": _PAGE_SIZE_DEFAULT, "string_items": True,
            "string_field": "product",
        },
    }

    # Details streams: parent list source + per-id detail endpoint.
    DETAILS_STREAMS: dict[str, dict] = {
        "campaigns_details": {
            "list_table": "campaigns", "detail_path": "/campaigns/details",
            "id_param": "campaign_id", "id_field": "campaign_id",
        },
        "canvases_details": {
            "list_table": "canvases", "detail_path": "/canvas/details",
            "id_param": "canvas_id", "id_field": "canvas_id",
        },
        "segments_details": {
            "list_table": "segments", "detail_path": "/segments/details",
            "id_param": "segment_id", "id_field": "segment_id",
        },
    }

    # Fan-out analytics streams: parent list source + per-parent data_series call.
    FANOUT_STREAMS: dict[str, dict] = {
        "campaigns_analytics": {
            "list_table": "campaigns", "data_path": "/campaigns/data_series",
            "records_key": "data", "id_param": "campaign_id", "id_field": "campaign_id",
        },
        "canvases_analytics": {
            "list_table": "canvases", "data_path": "/canvas/data_series",
            "records_key": "data.stats", "id_param": "canvas_id", "id_field": "canvas_id",
        },
        "segments_analytics": {
            "list_table": "segments", "data_path": "/segments/data_series",
            "records_key": "data", "id_param": "segment_id", "id_field": "segment_id",
        },
        "events_analytics": {
            "list_table": "events", "data_path": "/events/data_series",
            "records_key": "data", "id_param": "event", "id_field": "event",
        },
        "cards_analytics": {
            "list_table": "cards", "data_path": "/feed/data_series",
            "records_key": "data", "id_param": "card_id", "id_field": "card_id",
        },
    }

    # Workspace-level date-windowed series (no fan-out).
    WORKSPACE_STREAMS: dict[str, dict] = {
        "kpi_daily_new_users": {"data_path": "/kpi/new_users/data_series", "records_key": "data"},
        "kpi_daily_active_users": {"data_path": "/kpi/dau/data_series", "records_key": "data"},
        "kpi_monthly_active_users": {"data_path": "/kpi/mau/data_series", "records_key": "data"},
        "kpi_daily_app_uninstalls": {"data_path": "/kpi/uninstalls/data_series", "records_key": "data"},
        "purchases_quantity_series": {"data_path": "/purchases/quantity_series", "records_key": "data"},
        "purchases_revenue_series": {"data_path": "/purchases/revenue_series", "records_key": "data"},
    }

    # sends_analytics is special: it fans out over (campaign_id, send_id) pairs
    # which /campaigns/list does not expose. Handled explicitly in braze.py.
    SENDS_DATA_PATH = "/sends/data_series"


    def table_kind(table_name: str) -> str:
        """Return the read "kind" for a table."""
        if table_name in LIST_STREAMS:
            return KIND_SNAPSHOT_LIST
        if table_name in DETAILS_STREAMS:
            return KIND_DETAILS
        if table_name in FANOUT_STREAMS or table_name == "sends_analytics":
            return KIND_FANOUT_ANALYTICS
        if table_name in WORKSPACE_STREAMS:
            return KIND_WORKSPACE_SERIES
        raise ValueError(f"Unknown Braze table: {table_name!r}")


    ########################################################
    # src/databricks/labs/community_connector/sources/braze/braze.py
    ########################################################

    _COMPLEX_JSON_FIELDS: dict[str, tuple[str, ...]] = {
        "campaigns_details": ("messages", "conversion_behaviors"),
        "campaigns_analytics": ("messages",),
        "canvases_details": ("variants", "steps"),
        "canvases_analytics": ("variant_stats", "step_stats"),
        "sends_analytics": ("messages",),
    }

    # Fields kept as an explicit StructType — coerce an empty/absent object to None
    # (an empty dict is illegal for a Spark StructType field).
    _STRUCT_FIELDS: dict[str, tuple[str, ...]] = {
        "canvases_analytics": ("total_stats",),
    }

    # Safety cap on list-endpoint pagination so a misbehaving source can never spin
    # forever. 100k pages * 100/page is far beyond any real Braze workspace.
    _MAX_LIST_PAGES = 100_000

    # Optional passthrough query params, restricted to the endpoints that document
    # each (see _apply_optional_params).
    _APP_ID_TABLES = frozenset(
        {
            "events_analytics",
            "kpi_daily_new_users",
            "kpi_daily_active_users",
            "kpi_monthly_active_users",
            "kpi_daily_app_uninstalls",
            "purchases_quantity_series",
            "purchases_revenue_series",
        }
    )
    _UNIT_TABLES = frozenset(
        {"events_analytics", "purchases_quantity_series", "purchases_revenue_series"}
    )
    _PRODUCT_TABLES = frozenset(
        {"purchases_quantity_series", "purchases_revenue_series"}
    )


    class BrazeLakeflowConnect(LakeflowConnect, SupportsPartitionedStream):
        """LakeflowConnect + SupportsPartitionedStream implementation for Braze."""

        def __init__(self, options: dict[str, str]) -> None:
            super().__init__(options)

            base = (
                options.get("rest_endpoint")
                or options.get("base_url")
                or options.get("instance_url")
            )
            if not base:
                raise ValueError(
                    "Braze connector requires 'rest_endpoint' — the instance REST "
                    "base URL (e.g. 'https://rest.iad-01.braze.com'). Find it in the "
                    "Braze dashboard under Settings > APIs and Identifiers."
                )
            self._base_url = base.rstrip("/")

            api_key = (
                options.get("api_key")
                or options.get("access_token")
                or options.get("token")
            )
            if not api_key:
                raise ValueError(
                    "Braze connector requires 'api_key' — a Braze REST API key "
                    "(created under Settings > APIs and Identifiers > Rest API Keys)."
                )
            self._api_key = api_key

            self._include_deprecated = str(
                options.get("include_deprecated_streams", "true")
            ).strip().lower() in ("true", "1", "yes")

            # Freeze the upper bound at init time: midnight (UTC) of today. Using
            # the day boundary (not wall-clock now) means only COMPLETE days are
            # ingested, so consecutive intraday triggers never re-emit a partial
            # day's analytics (append tables have no upsert to dedup them). It is
            # also the constant returned by ``latest_offset`` that lets a
            # Trigger.AvailableNow micro-batch loop terminate.
            now = datetime.now(timezone.utc)
            midnight = now.replace(hour=0, minute=0, second=0, microsecond=0)
            self._until_iso = midnight.strftime("%Y-%m-%dT%H:%M:%SZ")

        # ------------------------------------------------------------------ #
        # LakeflowConnect interface
        # ------------------------------------------------------------------ #

        def list_tables(self) -> list[str]:
            tables = list(SUPPORTED_TABLES)
            if not self._include_deprecated:
                tables = [t for t in tables if t not in DEPRECATED_TABLES]
            return tables

        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            self._validate_table(table_name)
            return TABLE_SCHEMAS[table_name]

        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            self._validate_table(table_name)
            return dict(TABLE_METADATA[table_name])

        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """Single-driver read.

            Used by ``simpleStreamReader`` for the non-partitioned snapshot/details
            tables, and as a safe direct-call path for the partitioned append
            tables. Snapshot/details return offset ``{}`` (one full-refresh batch);
            append tables drain ``(since, until]`` and return ``{"cursor": until}``.
            """
            self._validate_table(table_name)
            kind = table_kind(table_name)
            if kind == KIND_SNAPSHOT_LIST:
                return self._read_list(table_name, table_options), {}
            if kind == KIND_DETAILS:
                return self._read_details(table_name, table_options), {}
            return self._read_analytics_batch(table_name, start_offset, table_options)

        # ------------------------------------------------------------------ #
        # SupportsPartitionedStream interface
        # ------------------------------------------------------------------ #

        def is_partitioned(self, table_name: str) -> bool:
            """Only date-windowed analytics streams are partitioned.

            Snapshot list and details streams have no server-side range query to
            split, so they fall back to ``simpleStreamReader`` (``read_table``).
            """
            if table_name not in SUPPORTED_TABLES:
                return False
            return table_kind(table_name) in (
                KIND_FANOUT_ANALYTICS,
                KIND_WORKSPACE_SERIES,
            )

        def latest_offset(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
        ) -> dict:
            """Return the init-time snapshot boundary (constant across the run).

            Returning a fixed value is what guarantees termination: once the
            committed offset reaches it, ``latest_offset == committed`` and the
            trigger stops. The next trigger builds a fresh connector with a newer
            boundary and ingests the delta.
            """
            self._validate_table(table_name)
            return {"cursor": self._until_iso}

        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
            end_offset: dict | None = None,
        ) -> Sequence[dict]:
            """Return partition descriptors.

            * Snapshot list / details tables: a single ``{"full": True}`` descriptor
              — the batch reader routes it to a full ``read_partition`` read (these
              tables never reach here on the streaming path; ``is_partitioned`` is
              False).
            * Append tables (batch: no offsets; streaming: ``(start, end]``): one
              partition per parent (fan-out) or a single windowed partition
              (workspace). Empty when there is no new data.
            """
            self._validate_table(table_name)
            kind = table_kind(table_name)
            if kind in (KIND_SNAPSHOT_LIST, KIND_DETAILS):
                return [{"full": True}]

            # Streaming quiescence: no new data since the last commit.
            if (
                start_offset is not None
                and end_offset is not None
                and start_offset == end_offset
            ):
                return []

            window = self._resolve_window(
                table_name, start_offset, end_offset, table_options
            )
            if window is None:
                return []
            since_iso, until_iso = window
            length = self._window_length(
                since_iso, until_iso, MAX_WINDOW_DAYS[table_name]
            )

            if table_name == "sends_analytics":
                return self._sends_partitions(length, until_iso, table_options)
            if kind == KIND_FANOUT_ANALYTICS:
                return self._fanout_partitions(table_name, length, until_iso, table_options)
            # workspace series -> a single windowed partition.
            return [{"length": length, "ending_at": until_iso}]

        def read_partition(
            self, table_name: str, partition: dict, table_options: dict[str, str]
        ) -> Iterator[dict]:
            """Read the records for one partition (runs on an executor)."""
            self._validate_table(table_name)
            kind = table_kind(table_name)
            if kind == KIND_SNAPSHOT_LIST:
                return self._read_list(table_name, table_options)
            if kind == KIND_DETAILS:
                return self._read_details(table_name, table_options)
            if table_name == "sends_analytics":
                return self._read_sends_partition(partition, table_options)
            if kind == KIND_FANOUT_ANALYTICS:
                return self._read_fanout_partition(table_name, partition, table_options)
            return self._read_workspace_partition(table_name, partition, table_options)

        # ------------------------------------------------------------------ #
        # Snapshot list reads
        # ------------------------------------------------------------------ #

        def _iter_list_items(
            self, list_table: str, table_options: dict[str, str]
        ) -> Iterator[Any]:
            """Yield raw items from a paginated list endpoint (0-indexed page).

            Stops on an empty page OR on the first short (< page_size) page — the
            latter is the documented last-page signal and also keeps the connector
            from issuing a redundant trailing page request.
            """
            cfg = LIST_STREAMS[list_table]
            path = cfg["path"]
            records_key = cfg["records_key"]
            page_size = cfg["page_size"]
            page = 0
            while page < _MAX_LIST_PAGES:
                body = self._get_json(path, params={"page": page})
                items = body.get(records_key) if isinstance(body, dict) else None
                if not items:
                    break
                yield from items
                if len(items) < page_size:
                    break
                page += 1

        def _read_list(
            self, table_name: str, table_options: dict[str, str]
        ) -> Iterator[dict]:
            cfg = LIST_STREAMS[table_name]
            records: list[dict] = []
            if cfg.get("string_items"):
                field = cfg["string_field"]
                for item in self._iter_list_items(table_name, table_options):
                    # Real API returns bare strings; the simulator corpus holds
                    # {field: value} dicts — accept both.
                    records.append(item if isinstance(item, dict) else {field: item})
            else:
                for item in self._iter_list_items(table_name, table_options):
                    if isinstance(item, dict):
                        records.append(item)
            return iter(records)

        def _discover_parents(
            self, list_table: str, table_options: dict[str, str]
        ) -> list[str]:
            """Return the parent ids/names driving a fan-out."""
            cfg = LIST_STREAMS[list_table]
            ids: list[str] = []
            if cfg.get("string_items"):
                field = cfg["string_field"]
                for item in self._iter_list_items(list_table, table_options):
                    value = item if isinstance(item, str) else item.get(field)
                    if value:
                        ids.append(value)
            else:
                for item in self._iter_list_items(list_table, table_options):
                    value = item.get("id") if isinstance(item, dict) else item
                    if value:
                        ids.append(value)
            return ids

        # ------------------------------------------------------------------ #
        # Details fan-out reads
        # ------------------------------------------------------------------ #

        def _read_details(
            self, table_name: str, table_options: dict[str, str]
        ) -> Iterator[dict]:
            cfg = DETAILS_STREAMS[table_name]
            id_param = cfg["id_param"]
            id_field = cfg["id_field"]
            json_fields = _COMPLEX_JSON_FIELDS.get(table_name, ())
            records: list[dict] = []
            for parent_id in self._discover_parents(cfg["list_table"], table_options):
                body = self._get_json(cfg["detail_path"], params={id_param: parent_id})
                # Real API: a single detail object at the top level (plus a
                # "message" envelope field). Simulator corpus: a JSON array — take
                # the first element and stamp the parent id so each fanned-out call
                # yields a distinct primary key.
                detail = body[0] if isinstance(body, list) and body else body
                if not isinstance(detail, dict):
                    continue
                rec = dict(detail)
                rec[id_field] = parent_id
                for f in json_fields:
                    if f in rec:
                        rec[f] = _json_str(rec[f])
                records.append(rec)
            return iter(records)

        # ------------------------------------------------------------------ #
        # Fan-out analytics reads
        # ------------------------------------------------------------------ #

        def _fanout_partitions(
            self,
            table_name: str,
            length: int,
            until_iso: str,
            table_options: dict[str, str],
        ) -> list[dict]:
            cfg = FANOUT_STREAMS[table_name]
            parents = self._discover_parents(cfg["list_table"], table_options)
            return [
                {"id": pid, "length": length, "ending_at": until_iso} for pid in parents
            ]

        def _read_fanout_partition(
            self, table_name: str, partition: dict, table_options: dict[str, str]
        ) -> Iterator[dict]:
            cfg = FANOUT_STREAMS[table_name]
            parent_id = partition["id"]
            params = {
                cfg["id_param"]: parent_id,
                "length": partition["length"],
                "ending_at": partition["ending_at"],
            }
            self._apply_optional_params(table_name, params, table_options)
            body = self._get_json(cfg["data_path"], params=params)
            stamp = {cfg["id_field"]: parent_id}
            records = _extract_records(body, cfg["records_key"])
            return iter(
                self._shape_analytics(table_name, raw, stamp) for raw in records
            )

        # ------------------------------------------------------------------ #
        # Workspace-level series reads
        # ------------------------------------------------------------------ #

        def _read_workspace_partition(
            self, table_name: str, partition: dict, table_options: dict[str, str]
        ) -> Iterator[dict]:
            cfg = WORKSPACE_STREAMS[table_name]
            params = {
                "length": partition["length"],
                "ending_at": partition["ending_at"],
            }
            self._apply_optional_params(table_name, params, table_options)
            body = self._get_json(cfg["data_path"], params=params)
            records = _extract_records(body, cfg["records_key"])
            # Workspace series carry only scalar fields — pass through as dicts.
            return iter(dict(raw) for raw in records if isinstance(raw, dict))

        # ------------------------------------------------------------------ #
        # sends_analytics (fan-out over campaign_id + send_id pairs)
        # ------------------------------------------------------------------ #

        def _sends_partitions(
            self, length: int, until_iso: str, table_options: dict[str, str]
        ) -> list[dict]:
            pairs = self._discover_send_pairs(table_options)
            return [
                {
                    "campaign_id": campaign_id,
                    "send_id": send_id,
                    "length": length,
                    "ending_at": until_iso,
                }
                for (campaign_id, send_id) in pairs
            ]

        def _discover_send_pairs(
            self, table_options: dict[str, str]
        ) -> list[tuple[str, str]]:
            """Resolve (campaign_id, send_id) pairs for ``/sends/data_series``.

            ``send_id`` is not exposed by ``/campaigns/list`` (Braze doc quirk #4),
            so unless the caller supplies pairs explicitly via the ``send_ids``
            table option (comma-separated ``campaign_id:send_id`` tokens), or a
            campaign record happens to carry a ``send_id`` field, no partitions are
            produced and the stream yields nothing — the documented behaviour when
            no send_id is available.
            """
            pairs: list[tuple[str, str]] = []
            raw = table_options.get("send_ids")
            if raw:
                for token in raw.split(","):
                    token = token.strip()
                    if ":" in token:
                        campaign_id, send_id = token.split(":", 1)
                        campaign_id, send_id = campaign_id.strip(), send_id.strip()
                        if campaign_id and send_id:
                            pairs.append((campaign_id, send_id))
            for item in self._iter_list_items("campaigns", table_options):
                if isinstance(item, dict) and item.get("send_id") and item.get("id"):
                    pairs.append((item["id"], item["send_id"]))
            return pairs

        def _read_sends_partition(
            self, partition: dict, table_options: dict[str, str]
        ) -> Iterator[dict]:
            params = {
                "campaign_id": partition["campaign_id"],
                "send_id": partition["send_id"],
                "length": partition["length"],
                "ending_at": partition["ending_at"],
            }
            body = self._get_json(SENDS_DATA_PATH, params=params)
            stamp = {
                "campaign_id": partition["campaign_id"],
                "send_id": partition["send_id"],
            }
            records = _extract_records(body, "data")
            return iter(
                self._shape_analytics("sends_analytics", raw, stamp) for raw in records
            )

        # ------------------------------------------------------------------ #
        # read_table drain for append tables
        # ------------------------------------------------------------------ #

        def _read_analytics_batch(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """Drain an append table's ``(since, until]`` window in one batch.

            Reuses ``get_partitions`` / ``read_partition`` so the single-driver path
            and the parallel path stay identical. Terminates when the committed
            cursor has reached the init-time boundary.
            """
            start_offset = start_offset or {}
            since_cursor = start_offset.get("cursor")
            if since_cursor and _cmp_iso(since_cursor, self._until_iso) >= 0:
                return iter([]), start_offset

            end_offset = {"cursor": self._until_iso}
            partitions = self.get_partitions(
                table_name, table_options, start_offset, end_offset
            )
            records: list[dict] = []
            for partition in partitions:
                records.extend(self.read_partition(table_name, partition, table_options))
            return iter(records), end_offset

        # ------------------------------------------------------------------ #
        # Record shaping
        # ------------------------------------------------------------------ #

        def _shape_analytics(
            self, table_name: str, raw: Any, stamp: dict[str, str]
        ) -> dict:
            """Stamp fan-out ids, JSON-encode dynamic objects, null empty structs."""
            rec = dict(raw) if isinstance(raw, dict) else {}
            rec.update(stamp)
            for f in _COMPLEX_JSON_FIELDS.get(table_name, ()):
                if f in rec:
                    rec[f] = _json_str(rec[f])
            for f in _STRUCT_FIELDS.get(table_name, ()):
                value = rec.get(f)
                rec[f] = value if isinstance(value, dict) and value else None
            return rec

        @staticmethod
        def _apply_optional_params(
            table_name: str, params: dict, table_options: dict[str, str]
        ) -> None:
            """Attach optional passthrough filters, only where the endpoint documents them.

            ``app_id`` is accepted by /events, /kpi/* and /purchases/* series (not by
            the campaign/canvas/segment/card analytics endpoints); ``unit`` by
            /events and /purchases/* series; ``segment_id`` by /events; ``product``
            by /purchases/* series.
            """
            if table_name in _APP_ID_TABLES and table_options.get("app_id"):
                params["app_id"] = table_options["app_id"]
            if table_name in _UNIT_TABLES and table_options.get("unit"):
                params["unit"] = table_options["unit"]
            if table_name == "events_analytics" and table_options.get("segment_id"):
                params["segment_id"] = table_options["segment_id"]
            if table_name in _PRODUCT_TABLES and table_options.get("product"):
                params["product"] = table_options["product"]

        # ------------------------------------------------------------------ #
        # Window resolution
        # ------------------------------------------------------------------ #

        def _resolve_window(
            self,
            table_name: str,
            start_offset: dict | None,
            end_offset: dict | None,
            table_options: dict[str, str],
        ) -> tuple[str, str] | None:
            """Resolve the ``(since, until]`` ISO window for an append read.

            ``until`` is the init-time boundary (capped). ``since`` is the committed
            cursor, or — on the first read — ``until`` minus ``history_days``
            (default: the endpoint's maximum window, so the first call is bounded
            and a single API request covers it). Returns None when the window is
            empty.
            """
            max_days = MAX_WINDOW_DAYS[table_name]
            history_days = _parse_int(table_options.get("history_days"), max_days, minimum=1)

            until_iso = (end_offset or {}).get("cursor") or self._until_iso
            if _cmp_iso(until_iso, self._until_iso) > 0:
                until_iso = self._until_iso

            start_cursor = (start_offset or {}).get("cursor")
            if start_cursor:
                since_iso = start_cursor
            else:
                since_iso = _format_iso(
                    _parse_iso(self._until_iso) - timedelta(days=history_days)
                )

            if _cmp_iso(since_iso, until_iso) >= 0:
                return None
            return since_iso, until_iso

        @staticmethod
        def _window_length(since_iso: str, until_iso: str, max_days: int) -> int:
            """Whole-day ``length`` for one API call, clamped to [1, max_days]."""
            delta = _parse_iso(until_iso) - _parse_iso(since_iso)
            days = math.ceil(delta.total_seconds() / 86400.0)
            return max(1, min(days, max_days))

        # ------------------------------------------------------------------ #
        # HTTP layer
        # ------------------------------------------------------------------ #

        @property
        def _session(self) -> requests.Session:
            """Lazily-built session so the connector carries no non-picklable state.

            Created on first use (driver or executor). Holding no threading.Lock
            keeps the instance cheap to serialise to Spark executors.
            """
            session = getattr(self, "_session_obj", None)
            if session is None:
                session = requests.Session()
                session.headers.update(
                    {
                        "Authorization": f"Bearer {self._api_key}",
                        "Content-Type": "application/json",
                        "Accept": "application/json",
                    }
                )
                self._session_obj = session
            return session

        def _request_with_retry(
            self, path: str, params: dict | None = None
        ) -> requests.Response:
            """GET with retry on 429/5xx, honouring ``X-RateLimit-Reset`` on 429."""
            url = f"{self._base_url}{path}"
            backoff = INITIAL_BACKOFF
            resp: requests.Response | None = None
            for attempt in range(MAX_RETRIES):
                resp = self._session.get(url, params=params, timeout=REQUEST_TIMEOUT)
                if resp.status_code not in RETRIABLE_STATUS_CODES:
                    return resp
                if attempt < MAX_RETRIES - 1:
                    time.sleep(self._retry_wait(resp, backoff))
                    backoff *= 2
            return resp  # type: ignore[return-value]

        @staticmethod
        def _retry_wait(resp: requests.Response, backoff: float) -> float:
            """Seconds to wait before a retry.

            On 429 respect ``X-RateLimit-Reset`` (UTC epoch seconds), capped so a
            stale/absurd header can't stall a run; otherwise exponential backoff.
            """
            if resp.status_code == 429:
                reset = resp.headers.get("X-RateLimit-Reset")
                if reset:
                    try:
                        delta = float(reset) - time.time()
                    except (TypeError, ValueError):
                        delta = 0.0
                    if delta > 0:
                        return min(delta, 60.0)
            return backoff

        def _get_json(self, path: str, params: dict | None = None) -> Any:
            """Issue a GET and return parsed JSON (dict or list); raise on error."""
            resp = self._request_with_retry(path, params=params)
            if not 200 <= resp.status_code < 300:
                raise RuntimeError(
                    f"Braze API error {resp.status_code} for {path}: "
                    f"{_error_detail(resp)}"
                )
            try:
                return resp.json()
            except ValueError:
                return {}

        # ------------------------------------------------------------------ #
        # Helpers
        # ------------------------------------------------------------------ #

        def _validate_table(self, table_name: str) -> None:
            if table_name not in SUPPORTED_TABLES:
                raise ValueError(
                    f"Unsupported Braze table {table_name!r}; supported: "
                    f"{list(SUPPORTED_TABLES)}"
                )


    # ---------------------------------------------------------------------------
    # Module-level helpers
    # ---------------------------------------------------------------------------


    def _extract_records(body: Any, records_key: str) -> list:
        """Extract the record array at a dotted key (``data`` / ``data.stats``)."""
        cur: Any = body
        for part in records_key.split("."):
            if isinstance(cur, dict):
                cur = cur.get(part)
            else:
                return []
        return cur if isinstance(cur, list) else []


    def _json_str(value: Any) -> str | None:
        """Encode a dynamic nested value as a JSON string.

        ``None`` stays ``None``; an existing string is passed through unchanged (the
        simulator corpus supplies bare strings for these fields); everything else is
        JSON-encoded so the column stays a plain ``StringType``.
        """
        if value is None:
            return None
        if isinstance(value, str):
            return value
        try:
            return json.dumps(value, ensure_ascii=False)
        except (TypeError, ValueError):
            return None


    def _error_detail(resp: requests.Response) -> str:
        """Best-effort extraction of Braze's ``{"message", "errors"}`` envelope."""
        try:
            body = resp.json()
        except ValueError:
            return (resp.text or "")[:256]
        if isinstance(body, dict):
            message = body.get("message")
            errors = body.get("errors")
            if errors:
                return f"{message}: {errors}"
            if message:
                return str(message)
        return str(body)[:256]


    def _parse_int(value: Any, default: int, *, minimum: int = 0) -> int:
        try:
            parsed = int(value)
        except (TypeError, ValueError):
            return default
        return parsed if parsed >= minimum else default


    def _parse_iso(iso_ts: str) -> datetime:
        """Parse an ISO-8601 timestamp (``Z`` or offset) as timezone-aware UTC."""
        normalised = iso_ts.replace("Z", "+00:00")
        dt = datetime.fromisoformat(normalised)
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=timezone.utc)
        return dt.astimezone(timezone.utc)


    def _format_iso(dt: datetime) -> str:
        return dt.astimezone(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


    def _cmp_iso(a: str, b: str) -> int:
        """Chronologically compare two ISO strings: -1 / 0 / 1."""
        da, db = _parse_iso(a), _parse_iso(b)
        if da < db:
            return -1
        if da > db:
            return 1
        return 0


    ########################################################
    # src/databricks/labs/community_connector/sparkpds/lakeflow_datasource.py
    ########################################################

    LakeflowConnectImpl = BrazeLakeflowConnect
    # Constant option or column names
    METADATA_TABLE = "_community_table_metadata"
    NAMESPACES_TABLE = "_community_namespaces"
    TABLES_TABLE = "_community_tables"
    VIRTUAL_TABLES = (METADATA_TABLE, NAMESPACES_TABLE, TABLES_TABLE)
    TABLE_NAME = "tableName"
    TABLE_NAME_LIST = "tableNameList"
    TABLE_CONFIGS = "tableConfigs"
    IS_DELETE_FLOW = "isDeleteFlow"
    NAMESPACE_PREFIX = "namespacePrefix"
    NAMESPACE = "namespace"


    def _decode_list_of_str_option(option_name: str, value: str | None) -> list[str] | None:
        """Decode and validate a JSON-encoded ``list[str]`` Spark option.

        Returns ``None`` if the option is absent; otherwise the parsed list.
        Raises ``ValueError`` with the offending value if the JSON is malformed
        or the decoded value is not a list of strings.
        """
        if value is None:
            return None
        try:
            decoded = json.loads(value)
        except json.JSONDecodeError as e:
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded list[str]; "
                f"got non-JSON value: {value!r}"
            ) from e
        if not isinstance(decoded, list) or not all(isinstance(s, str) for s in decoded):
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded list[str]; "
                f"got: {decoded!r}"
            )
        return decoded


    def _decode_dict_option(option_name: str, value: str | None) -> dict:
        """Decode and validate a JSON-encoded ``dict`` Spark option."""
        if value is None:
            return {}
        try:
            decoded = json.loads(value)
        except json.JSONDecodeError as e:
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded dict; "
                f"got non-JSON value: {value!r}"
            ) from e
        if not isinstance(decoded, dict):
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded dict; got: {decoded!r}"
            )
        return decoded


    # PySpark's DataSource API requires camelCase method names and inherits
    # semantics from the parent class, so per-method docstrings are redundant.
    # pylint: disable=invalid-name,missing-function-docstring
    class LakeflowStreamReader(SimpleDataSourceStreamReader, SupportsTriggerAvailableNow):
        """
        Implements a data source stream reader for Lakeflow Connect.
        Currently, only the simpleStreamReader is implemented, which uses a
        more generic protocol suitable for most data sources that support
        incremental loading.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.lakeflow_connect = lakeflow_connect
            self.schema = schema

        def initialOffset(self):
            return {}

        def read(self, start: dict) -> (Iterator[tuple], dict):
            is_delete_flow = self.options.get(IS_DELETE_FLOW) == "true"
            # Strip delete flow options before passing to connector
            table_options = {
                k: v for k, v in self.options.items() if k != IS_DELETE_FLOW
            }

            if is_delete_flow:
                records, offset = self.lakeflow_connect.read_table_deletes(
                    self.options[TABLE_NAME], start, table_options
                )
            else:
                records, offset = self.lakeflow_connect.read_table(
                    self.options[TABLE_NAME], start, table_options
                )
            rows = map(lambda x: parse_value(x, self.schema), records)
            return rows, offset

        def readBetweenOffsets(self, start: dict, end: dict) -> Iterator[tuple]:
            # TODO: This does not ensure the records returned are identical across repeated calls.
            # For append-only tables, the data source must guarantee that reading from the same
            # start offset will always yield the same set of records.
            # For tables ingested as incremental CDC, it is only necessary that no new changes
            # are missed in the returned records.
            return self.read(start)[0]

        def prepareForTriggerAvailableNow(self) -> None:
            # No need to do anything special here. Everything is handled in the __init__ method.
            pass


    class LakeflowPartitionedStreamReader(DataSourceStreamReader, SupportsTriggerAvailableNow):
        """Proxy that bridges SupportsPartitionedStream to PySpark's DataSourceStreamReader.

        Used when a connector implements the SupportsPartitionedStream mixin to
        support partitioned streaming reads across Spark executors.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self.table_options = {k: v for k, v in options.items() if k != IS_DELETE_FLOW}

        def initialOffset(self):
            return {}

        def getDefaultReadLimit(self):
            # Admission control is the connector's responsibility (e.g. via
            # window_days, max_records_per_batch), not the engine's.  Always
            # ask the engine for ReadAllAvailable.
            return ReadAllAvailable()

        def latestOffset(self, start: dict, limit) -> dict:
            # We declared ReadAllAvailable via getDefaultReadLimit; the engine
            # must respect it.  Anything else means admission-control expectations
            # we do not support — fail loudly rather than silently ignore.
            if not isinstance(limit, ReadAllAvailable):
                raise ValueError(
                    f"LakeflowPartitionedStreamReader only supports ReadAllAvailable; "
                    f"got {type(limit).__name__}. Micro-batch sizing must be controlled "
                    f"by the connector implementation (table_options), not the engine."
                )
            return self.lakeflow_connect.latest_offset(
                self.table_name, self.table_options, start
            )

        def partitions(self, start: dict, end: dict):
            partition_descs = self.lakeflow_connect.get_partitions(
                self.table_name, self.table_options, start, end
            )
            return [InputPartition(json.dumps(p)) for p in partition_descs]

        def read(self, partition: InputPartition):
            partition_desc = json.loads(partition.value)
            records = self.lakeflow_connect.read_partition(
                self.table_name, partition_desc, self.table_options
            )
            return map(lambda x: parse_value(x, self.schema), records)

        def prepareForTriggerAvailableNow(self) -> None:
            # No need to do anything special here. Everything is handled in the __init__ method.
            pass


    class LakeflowBatchReader(DataSourceReader):
        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self._supports_partition = isinstance(lakeflow_connect, SupportsPartition)

        def partitions(self):
            if self._supports_partition and self.table_name not in VIRTUAL_TABLES:
                try:
                    partition_descs = self.lakeflow_connect.get_partitions(
                        self.table_name, self.options
                    )
                    return [InputPartition(json.dumps(p)) for p in partition_descs]
                except Exception:
                    self._supports_partition = False
            return [InputPartition(None)]

        def read(self, partition):
            if self.table_name == METADATA_TABLE:
                records = self._read_table_metadata()
            elif self.table_name == NAMESPACES_TABLE:
                records = self._read_namespaces()
            elif self.table_name == TABLES_TABLE:
                records = self._read_tables()
            elif self._supports_partition and partition.value is not None:
                partition_desc = json.loads(partition.value)
                records = self.lakeflow_connect.read_partition(
                    self.table_name, partition_desc, self.options
                )
            else:
                records, _ = self.lakeflow_connect.read_table(self.table_name, None, self.options)
            return map(lambda x: parse_value(x, self.schema), records)

        def _read_table_metadata(self):
            table_names = _decode_list_of_str_option(
                TABLE_NAME_LIST, self.options.get(TABLE_NAME_LIST)
            ) or []
            table_configs = _decode_dict_option(
                TABLE_CONFIGS, self.options.get(TABLE_CONFIGS)
            )
            all_records = []
            # Preserve caller-supplied table order — caller controls it.
            for table in table_names:
                metadata = self.lakeflow_connect.read_table_metadata(
                    table, table_configs.get(table, {})
                )
                all_records.append({TABLE_NAME: table, **metadata})
            return all_records

        def _read_namespaces(self):
            # Connectors without SupportsNamespaces are flat — no rows.
            if not isinstance(self.lakeflow_connect, SupportsNamespaces):
                return []
            prefix = _decode_list_of_str_option(
                NAMESPACE_PREFIX, self.options.get(NAMESPACE_PREFIX)
            )
            namespaces = self.lakeflow_connect.list_namespaces(prefix)
            # Sort framework-side for deterministic output regardless of
            # connector iteration order.
            return [{"namespace": ns} for ns in sorted(namespaces)]

        def _read_tables(self):
            namespace_supplied = NAMESPACE in self.options
            if isinstance(self.lakeflow_connect, SupportsNamespaces):
                if not namespace_supplied:
                    raise ValueError(
                        f"option '{NAMESPACE}' is required when reading "
                        f"'{TABLES_TABLE}' against a connector that implements "
                        f"SupportsNamespaces. Pass a JSON-encoded list[str] "
                        f"(use '[]' for root-level tables; walk the tree via "
                        f"'{NAMESPACES_TABLE}' to enumerate every namespace)."
                    )
                namespace = _decode_list_of_str_option(
                    NAMESPACE, self.options[NAMESPACE]
                )
                tables = self.lakeflow_connect.list_tables_in_namespace(namespace)
                return [
                    {"namespace": namespace, TABLE_NAME: tn}
                    for tn in sorted(tables)
                ]
            # Flat connector path. Reject a stray `namespace` option — the
            # caller probably mistook this connector for namespace-aware and
            # silently ignoring the option would mask the bug.
            if namespace_supplied:
                raise ValueError(
                    f"option '{NAMESPACE}' was supplied but the connector does "
                    f"not implement SupportsNamespaces. Either omit the option "
                    f"or use a namespace-aware connector."
                )
            return [
                {"namespace": [], TABLE_NAME: tn}
                for tn in sorted(self.lakeflow_connect.list_tables())
            ]


    class LakeflowSource(DataSource):
        """
        PySpark DataSource base for Lakeflow Connect.

        Two ways the connector implementation is bound:

        - Per-source subclass (wheel / multi-file deployment): subclass and set
          ``_lakeflow_connect_cls``::

              class GmailDataSource(LakeflowSource):
                  _lakeflow_connect_cls = GmailLakeflowConnect

              spark.dataSource.register(GmailDataSource)

        - Merged single-file deployment (SDP): ``_lakeflow_connect_cls`` is left
          ``None`` and the connector is taken from the module-level
          ``LakeflowConnectImpl`` placeholder, which the merge script substitutes
          with the actual implementation class.
        """

        # Per-source subclasses set this. Left ``None`` on the base so the merged
        # single-file path falls back to the ``LakeflowConnectImpl`` placeholder.
        _lakeflow_connect_cls = None

        # Spark format name. Defaults to "lakeflow_connect" because Unity Catalog
        # connection-option injection looks for that exact string. A per-source
        # subclass may override this with its source name once it no longer relies
        # on UC injection (see the commented override in each source's __init__.py).
        _format_name = "lakeflow_connect"

        def __init__(self, options):
            self.options = options
            table = options.get(TABLE_NAME)
            # Catch typos against the framework's reserved virtual-table namespace
            # early — falling through to the connector with an unknown
            # `_community_*` name yields a confusing per-connector error.
            if table and table.startswith("_community_") and table not in VIRTUAL_TABLES:
                raise ValueError(
                    f"unknown framework virtual table '{table}'. Valid framework "
                    f"virtual tables are: {', '.join(VIRTUAL_TABLES)}. "
                    f"For a regular source table, use a name that does not start "
                    f"with '_community_'."
                )
            # Per-source subclasses bind the implementation via _lakeflow_connect_cls.
            # The merged single-file path leaves it None and relies on the
            # LakeflowConnectImpl placeholder (substituted by the merge script).
            connect_cls = type(self)._lakeflow_connect_cls or LakeflowConnectImpl
            self.lakeflow_connect = connect_cls(options)  # pylint: disable=abstract-class-instantiated

        @classmethod
        def name(cls):
            return cls._format_name

        def schema(self):
            table = self.options[TABLE_NAME]
            if table == METADATA_TABLE:
                return StructType(
                    [
                        StructField(TABLE_NAME, StringType(), False),
                        StructField("primary_keys", ArrayType(StringType()), True),
                        StructField("cursor_field", StringType(), True),
                        StructField("ingestion_type", StringType(), True),
                    ]
                )
            if table == NAMESPACES_TABLE:
                return StructType(
                    [
                        StructField("namespace", ArrayType(StringType()), False),
                    ]
                )
            if table == TABLES_TABLE:
                return StructType(
                    [
                        StructField("namespace", ArrayType(StringType()), False),
                        StructField(TABLE_NAME, StringType(), False),
                    ]
                )
            return self.lakeflow_connect.get_table_schema(table, self.options)

        def reader(self, schema: StructType):
            return LakeflowBatchReader(self.options, schema, self.lakeflow_connect)

        def streamReader(self, schema: StructType):
            # Use the partitioned DataSourceStreamReader when the connector
            # implements SupportsPartitionedStream and the table opts in.
            # Otherwise, delegate to super() which raises PySparkNotImplementedError,
            # causing Spark to fall back to simpleStreamReader().
            if isinstance(self.lakeflow_connect, SupportsPartitionedStream):
                table = self.options[TABLE_NAME]
                if self.lakeflow_connect.is_partitioned(table):
                    return LakeflowPartitionedStreamReader(self.options, schema, self.lakeflow_connect)
            return super().streamReader(schema)

        def simpleStreamReader(self, schema: StructType):
            return LakeflowStreamReader(self.options, schema, self.lakeflow_connect)


    spark.dataSource.register(LakeflowSource)
